title: Christina B. # your name (or website title) here
logo: "/images/4A4A8103.jpg?raw=true" # your photo (or logo) here https://github.com/christina-b68/christina-b68.github.io/commit/b263841365d392c15762c04ac0e7d8e861da1fa7#diff-9e219f15b345645d38b741b04b2b37d2
description: > # your text below (remove <br> elements if you don't need line breaks)
  A folk with a huge passion for data science...
  <br><br>
  Give me a dataset, I will tell you a story!
  <br><br>
  <a href="https://www.linkedin.com/in/christina-bui1368/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
